layout:
  screens:
    - name: Host info
      # Stack from left to right
      stack: horizontal
      children:
        # Actual pane
        - stack: vertical
          children:
            - name: Local time
              module: clock
              config:
                timezone: Local
                format: 15:04:05 MST
            - name: America PST
              module: clock
              config:
                timezone: America/Los_Angeles
                format: 15:04:05 MST
        # Pane including children stacked top to bottom
        - stack: vertical
          children:
            - name: Host metrics
              module: host-metrics
              config:
                cpu:
                memory:
                  unit: mb
                disk:
                  unit: mb
            - name: Weather
              module: graph
              config:
                type: line
                source:
                  file: ~/some/timeseries-data.csv
