name: build
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  buildandtest:
    name: Build and test
    strategy:
      matrix:
        go-version: [~1.21.5, ^1]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download

      - name: Ensure we can build
        run: go build -v ./cmd/yakdash

      - name: Test
        run: make test
