name: build
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  buildandtest:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.5

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Go modules
        run: go mod download

      - name: Ensure we can build
        run: go build -v ./cmd/yakdash

      - name: Test
        run: make test
